### Databases

db_ctl:
  type: psql
  host: localhost
  port: 5432
  database: bricolage
  username: bricolage
  # Get password from password.yml
  password: <%= password 'postgres_bricolage_password' %>
  encoding: utf8

db_data: &db_data
  type: psql
  host: redshift.host
  port: 5439
  database: production
  username: bricolage
  # Get password from password.yml
  password: <%= password 'redshift_bricolage_password' %>
  encoding: utf8

sql:
  <<: *db_data

### SQS

sqs_event:
  type: sqs
  region: ap-northeast-1
  url: https://sqs.ap-northeast-1.amazonaws.com/111111111111/bricolage-events
  max_number_of_messages: 10
  visibility_timeout: 600
  wait_time_seconds: 10
  # Enable following lines if you use access key explicitly.
  # Otherwise Bricolage uses EC2 instance or ECS task attached IAM role.
  #access_key_id: "<%%= password 'aws_access_key_id' %>"
  #secret_access_key: "<%%= password 'aws_secret_access_key' %>"

sqs_task:
  type: sqs
  region: ap-northeast-1
  url: https://sqs.ap-northeast-1.amazonaws.com/111111111111/bricolage-tasks
  max_number_of_messages: 1
  visibility_timeout: 1800
  wait_time_seconds: 10
  # Enable following lines if you use access key explicitly.
  # Otherwise Bricolage uses EC2 instance or ECS task attached IAM role.
  #access_key_id: "<%%= password 'aws_access_key_id' %>"
  #secret_access_key: "<%%= password 'aws_secret_access_key' %>"

### S3

s3_ctl: &s3_ctl
  type: s3
  region: ap-northeast-1
  endpoint: s3-ap-northeast-1.amazonaws.com
  bucket: bricolagectl.ap-northeast-1
  prefix: development/strload
  # Enable following lines if you use access key explicitly.
  # Otherwise Bricolage uses EC2 instance or ECS task attached IAM role.
  #access_key_id: "<%%= password 'aws_access_key_id' %>"
  #secret_access_key: "<%%= password 'aws_secret_access_key' %>"

s3:
  <<: *s3_ctl
