# Never commit this file
redshift_bricolage_password: xxxxxxxxxxx
postgres_bricolage_password: xxxxxxxxxxx
aws_access_key_id: "AKIAAAAAAAAAAAAAAAAA"
aws_secret_access_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
